// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MCQcCDz2rvkxxOe8lOz4egd395hhmj0',
    appId: '1:28247345869:web:62b34324edd4ac84c6f784',
    messagingSenderId: '28247345869',
    projectId: 'e-commerceapp-7a367',
    authDomain: 'e-commerceapp-7a367.firebaseapp.com',
    storageBucket: 'e-commerceapp-7a367.firebasestorage.app',
    measurementId: 'G-302SEMN0NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sgQzj4C_e4OI8gOSVjFf_ouwEOaudHY',
    appId: '1:28247345869:android:b86a1ee3512c9ed0c6f784',
    messagingSenderId: '28247345869',
    projectId: 'e-commerceapp-7a367',
    storageBucket: 'e-commerceapp-7a367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Iw3bPNxLngti4i8WgXhzV6mrYRo0Hmo',
    appId: '1:28247345869:ios:15dfe411a9c95df7c6f784',
    messagingSenderId: '28247345869',
    projectId: 'e-commerceapp-7a367',
    storageBucket: 'e-commerceapp-7a367.firebasestorage.app',
    iosBundleId: 'com.dragorrik.eCommerceApp',
  );
}
